### ISSUE TITLE
Error when there is a dash in field name

### ISSUE THREAD

**Issue by mohsen1** [json-schema-form/angular-schema-form#168]
If my model has property with dash in it, I will get the following errors. 

``` js
Error: [ngModel:nonassign] Expression 'model.X-Test' is non-assignable. Element: <input ng-show="form.key" type="{{form.type}}" step="any" sf-changed="form" placeholder="{{form.placeholder}}" class="form-control" ng-model-options="form.ngModelOptions" ng-model="model.X-Test" ng-disabled="form.readonly" schema-validate="form">
http://errors.angularjs.org/1.2.15/ngModel/nonassign?p0=model.X-Test&p1=%3C…t%22%20ng-disabled%3D%22form.readonly%22%20schema-validate%3D%22form%22%3E
    at http://0.0.0.0:9000/bower_components/angular/angular.js:78:12
    at new NgModelController (http://0.0.0.0:9000/bower_components/angular/angular.js:16922:28)
    at invoke (http://0.0.0.0:9000/bower_components/angular/angular.js:3805:17)
    at Object.instantiate (http://0.0.0.0:9000/bower_components/angular/angular.js:3816:23)
    at $get (http://0.0.0.0:9000/bower_components/angular/angular.js:6922:28)
    at http://0.0.0.0:9000/bower_components/angular/angular.js:6309:34
    at forEach (http://0.0.0.0:9000/bower_components/angular/angular.js:330:20)
    at nodeLinkFn (http://0.0.0.0:9000/bower_components/angular/angular.js:6296:11)
    at compositeLinkFn (http://0.0.0.0:9000/bower_components/angular/angular.js:5761:15)
    at nodeLinkFn (http://0.0.0.0:9000/bower_components/angular/angular.js:6344:24) 
```

From what I see, it's trying to access `model.X-Test` which is invalid JS. From my little research it could be related to `$$value` expression [here](https://github.com/Textalk/angular-schema-form/blob/9a1b9363ab0a17f585344b61379a3b854da2c72e/src/directives/decorators/bootstrap/default.html#L11)

**Comment by ajit-drag** [comment]
Not working in form binding. I am using <select ... ng-model="staff.member-Type">. But still facing same issue. what could be the possible solution. As JSON format cant be changed.

**Comment by Anthropic** [comment]
@ajit-drag you need to make a plunker or gist or provide exampes if you want people to understand your issue.

**Comment by margi212** [comment]
Same issue face @ajit-drag 
Did you find nay Solution?
