### ISSUE TITLE
Tab array broken in Chrome

### ISSUE THREAD

**Issue by oivinds** [json-schema-form/angular-schema-form#499]
Cloned repo, ran examples/bootstrap-example.html and selected the "tab array" example
In Chrome console I got this error:
```
Error: [$parse:syntax] http://errors.angularjs.org/1.4.3/$parse/syntax?p0=.&p1=not%20a%20primary%20expression&p2=1&p3=.length&p4=.length
    at Error (native)
    at http://localhost/angular-schema-form/bower_components/angular/angular.min.js:6:416
    at Object.q.throwError (http://localhost/angular-schema-form/bower_components/angular/angular.min.js:209:32)
    at Object.q.primary (http://localhost/angular-schema-form/bower_components/angular/angular.min.js:206:6)
    at Object.q.unary (http://localhost/angular-schema-form/bower_components/angular/angular.min.js:205:174)
    at Object.q.multiplicative (http://localhost/angular-schema-form/bower_components/angular/angular.min.js:204:434)
    at Object.q.additive (http://localhost/angular-schema-form/bower_components/angular/angular.min.js:204:261)
    at Object.q.relational (http://localhost/angular-schema-form/bower_components/angular/angular.min.js:204:96)
    at Object.q.equality (http://localhost/angular-schema-form/bower_components/angular/angular.min.js:203:425)
    at Object.q.logicalAND (http://localhost/angular-schema-form/bower_components/angular/angular.min.js:203:278) <li ng-hide="form.readonly" ng-click="$event.preventDefault() || (selected.tab = appendToArray().length - 1)">(anonymous function) @ angular.js:12330$get @ angular.js:9109Y @ angular.js:8652S @ angular.js:8150g @ angular.js:7541S @ angular.js:8145g @ angular.js:7541S @ angular.js:8145g @ angular.js:7541(anonymous function) @ angular.js:7416$get.h @ angular.js:7560s @ angular.js:8177(anonymous function) @ angular.js:23812scopePrototype.$watch.arguments.(anonymous function) @ hint.js:1905$get.n.$digest @ angular.js:15683scopePrototype.$digest @ hint.js:1924$get.n.$apply @ angular.js:15951scopePrototype.$apply @ hint.js:1987l @ angular.js:10364F @ angular.js:10536K.onload @ angular.js:10477

```

**Comment by nicklasb** [comment]
Have you installed all dependencies?

**Comment by Anthropic** [comment]
You could also check if you are running as a file or through a http server.
Please re-open if you have more info to help us answer more sufficiently.

**Comment by grobgl** [comment]
Came across the same issue. Turned out that I accidentally put `ng-field-model` instead of `sf-field-model` in my template. Make sure that you have the following attributes at the beginning of your tabarray template:
```
ng-model="modelArray"
schema-validate="form"
sf-field-model="sf-new-array"
sf-new-array
````
