### ISSUE TITLE
empty properties in schema

### ISSUE THREAD

**Issue by gioppoluca** [json-schema-form/angular-schema-form#595]
I'm generating the properties of the schema dynamically and there could be the case of no fields needed for some use cases.
In this event the form is like:

```
[
  "*",
  {
    "type": "submit",
    "title": "OK"
  }
]
```

While the schema is:

```
{
  "type": "object",
  "title": "Types",
  "properties": {}
}
```

I'm expecting to have an empty form with just the submit button instead I get nothing.
Any hint?
Thanks

**Comment by apinnecke** [comment]
+1

I'm facing the very same problem. During re-rendering a form due to schema changes, the form stays the same if properties is an empty array. But if there is at least one single property, it replaces the old form.

You may fix this by removing [this line](https://github.com/Textalk/angular-schema-form/blob/development/src/directives/schema-form.js#L161), but then you're receiving the following set of  errors, first one in [this line](https://github.com/Textalk/angular-schema-form/blob/development/src/directives/field.js#L160)

```
TypeError: Cannot read property 'key' of undefined
    at angular.module.directive.sfSelect.link.post (http://localhost:3000/app.js:2082:21)
    at invokeLinkFn (http://localhost:3000/app.js:63716:9)
    at nodeLinkFn (http://localhost:3000/app.js:63216:11)
    at compositeLinkFn (http://localhost:3000/app.js:62607:13)
    at publicLinkFn (http://localhost:3000/app.js:62482:30)
    at angular.module.directive.sfBuilder.link.internalRender (http://localhost:3000/app.js:2645:39)
    at angular.module.directive.sfBuilder.link.render (http://localhost:3000/app.js:2590:13)
    at Object.<anonymous> (http://localhost:3000/app.js:2676:13)
    at Scope.$digest (http://localhost:3000/app.js:70745:40)
    at Scope.$apply (http://localhost:3000/app.js:71024:24) <div class="form-group schema-form-text  ng-scope" ng-class="{'has-error': form.disableErrorState !== true &amp;&amp; hasError(), 'has-success': form.disableSuccessState !== true &amp;&amp; hasSuccess(), 'has-feedback': form.feedback !== false }" sf-field="1">(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246invokeLinkFn @ angular.js:8791nodeLinkFn @ angular.js:8289compositeLinkFn @ angular.js:7680publicLinkFn @ angular.js:7555angular.module.directive.sfBuilder.link.internalRender @ schema-form.js:2644angular.module.directive.sfBuilder.link.render @ schema-form.js:2589(anonymous function) @ schema-form.js:2675Scope.$digest @ angular.js:15818Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:28525eventHandler @ angular.js:3298
angular.js:12477 TypeError: Cannot read property 'key' of undefined
    at angular.module.directive.sfSelect.link.post (http://localhost:3000/app.js:2082:21)
    at invokeLinkFn (http://localhost:3000/app.js:63716:9)
    at nodeLinkFn (http://localhost:3000/app.js:63216:11)
    at compositeLinkFn (http://localhost:3000/app.js:62607:13)
    at publicLinkFn (http://localhost:3000/app.js:62482:30)
    at angular.module.directive.sfBuilder.link.internalRender (http://localhost:3000/app.js:2645:39)
    at angular.module.directive.sfBuilder.link.render (http://localhost:3000/app.js:2590:13)
    at Object.<anonymous> (http://localhost:3000/app.js:2676:13)
    at Scope.$digest (http://localhost:3000/app.js:70745:40)
    at Scope.$apply (http://localhost:3000/app.js:71024:24) <div class="form-group schema-form-number  has-success ng-scope" ng-class="{'has-error': form.disableErrorState !== true &amp;&amp; hasError(), 'has-success': form.disableSuccessState !== true &amp;&amp; hasSuccess(), 'has-feedback': form.feedback !== false }" sf-field="3">(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246invokeLinkFn @ angular.js:8791nodeLinkFn @ angular.js:8289compositeLinkFn @ angular.js:7680publicLinkFn @ angular.js:7555angular.module.directive.sfBuilder.link.internalRender @ schema-form.js:2644angular.module.directive.sfBuilder.link.render @ schema-form.js:2589(anonymous function) @ schema-form.js:2675Scope.$digest @ angular.js:15818Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:28525eventHandler @ angular.js:3298
angular.js:12477 TypeError: Cannot read property 'copyValueTo' of undefined
    at angular.module.directive.sfSelect.link (http://localhost:3000/app.js:2735:17)
    at invokeLinkFn (http://localhost:3000/app.js:63716:9)
    at nodeLinkFn (http://localhost:3000/app.js:63216:11)
    at compositeLinkFn (http://localhost:3000/app.js:62607:13)
    at publicLinkFn (http://localhost:3000/app.js:62482:30)
    at boundTranscludeFn (http://localhost:3000/app.js:62626:16)
    at controllersBoundTransclude (http://localhost:3000/app.js:63243:18)
    at Object.ngIfWatchAction [as fn] (http://localhost:3000/app.js:78989:15)
    at Scope.$digest (http://localhost:3000/app.js:70753:29)
    at Scope.$apply (http://localhost:3000/app.js:71024:24) <input ng-if="!form.fieldAddonLeft &amp;&amp; !form.fieldAddonRight" ng-show="form.key" type="text" step="any" sf-changed="form" placeholder="" class="form-control ng-pristine ng-untouched ng-valid ng-scope" id="user" sf-field-model="" ng-disabled="form.readonly" schema-validate="form" name="user" aria-describedby="userStatus" ng-model="model['user']" data-ng-animate="1">(anonymous function) @ angular.js:12477(anonymous function) @ angular.js:9246invokeLinkFn @ angular.js:8791nodeLinkFn @ angular.js:8289compositeLinkFn @ angular.js:7680publicLinkFn @ angular.js:7555boundTranscludeFn @ angular.js:7699controllersBoundTransclude @ angular.js:8316ngIfWatchAction @ angular.js:24062Scope.$digest @ angular.js:15826Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:28525eventHandler @ angular.js:3298
angular.js:12477 TypeError: Cannot read property 'copyValueTo' of undefined
    at angular.module.directive.sfSelect.link (http://localhost:3000/app.js:2735:17)
    at invokeLinkFn (http://localhost:3000/app.js:63716:9)
    at nodeLinkFn (http://localhost:3000/app.js:63216:11)
    at compositeLinkFn (http://localhost:3000/app.js:62607:13)
    at publicLinkFn (http://localhost:3000/app.js:62482:30)
    at boundTranscludeFn (http://localhost:3000/app.js:62626:16)
    at controllersBoundTransclude (http://localhost:3000/app.js:63243:18)
    at Object.ngIfWatchAction [as fn] (http://localhost:3000/app.js:78989:15)
    at Scope.$digest (http://localhost:3000/app.js:70753:29)
    at Scope.$apply (http://localhost:3000/app.js:71024:24) <input ng-if="!form.fieldAddonLeft &amp;&amp; !form.fieldAddonRight" ng-show="form.key" type="number" step="any" sf-changed="form" placeholder="" class="form-control ng-pristine ng-untouched ng-valid ng-scope" id="limit" sf-field-model="" ng-disabled="form.readonly" schema-validate="form" name="limit" aria-describedby="limitStatus" ng-model="model['limit']" data-ng-animate="1">
```

**Comment by Anthropic** [comment]
If you find the code `&& Object.keys(schema.properties).length > 0` and remove it, then add `{"key":"submit", "type": "hidden"}` to your form it would work. I'll look into something more permanent though.

**Comment by Anthropic** [comment]
This should be working in the alpha now :)
