### ISSUE TITLE
Can't include with browserify

### ISSUE THREAD

**Issue by Alain1405** [json-schema-form/angular-schema-form#713]
Hi, I've installed `angular-schema-form` with npm and I'm trying to include it into my project with browserify, but I get the error below. I've tried  including `angular-sanitize` or `bootstrap-decorators` in the right order but no success. 
My code:
```
var angular = require('angular');
var angularSanitize = require('angular-sanitize');
var ngSchemaForm = require('angular-schema-form');
var bootstrapDecorator = require('angular-schema-form-bootstrap');
...

angular.module('infarm.main', [
        ...
        angularSanitize,
        ngSchemaForm,
        bootstrapDecorator
    ])

```
The installed deps:
```
    "angular": "^1.4.4",
    "angular-sanitize": "^1.5.6",
    "angular-schema-form": "^0.8.13",
    "angular-schema-form-bootstrap": "^0.2.0",
    "browserify": "^13.0.1",

```

Here is the error:

```
angular.js:68Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp.main due to:
Error: [$injector:modulerr] Failed to instantiate module {"_invokeQueue":[["$provide","provider",{"0":"sfPath","1":[null]}],["$provide","provider",{"0":"sfBuilder","1":["sfPathProvider",null]}],["$provide","provider",{"0":"schemaFormDecorators","1":["$compileProvider","sfPathProvider",null]}],["$provide","provider",{"0":"sfErrorMessage"}],["$provide","provider",{"0":"schemaForm","1":["sfPathProvider",null]}],["$provide","factory",{"0":"sfSelect","1":["sfPath",null]}],["$provide","factory",{"0":"sfValidator","1":[null]}],["$compileProvider","directive",{"0":"sfArray","1":["sfSelect","schemaForm","sfValidator","sfPath",null]}],["$compileProvider","directive",{"0":"sfChanged"}],["$compileProvider","directive",{"0":"sfField","1":["$parse","$compile","$http","$templateCache","$interpolate","$q","sfErrorMessage","sfPath","sfSelect",null]}],["$compileProvider","directive",{"0":"sfMessage","1":["$injector","sfErrorMessage",null]}],["$compileProvider","directive",{"0":"sfNewArray","1":["sfSelect","sfPath","schemaForm",null]}],["$compileProvider","directive",{"0":"sfSchema","1":["$compile","$http","$templateCache","$q","schemaForm","schemaFormDecorators","sfSelect","sfPath","sfBuilder",null]}],["$compileProvider","directive",{"0":"schemaValidate","1":["sfValidator","$parse","sfSelect",null]}]],"_configBlocks":[],"_runBlocks":[],"requires":[],"name":"schemaForm"} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object
http://errors.angularjs.org/1.5.2/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20Object
    at http://localhost:8000/dev/js/index.js:13039:12
    at assertArg (http://localhost:8000/dev/js/index.js:14815:11)
    at assertArgFn (http://localhost:8000/dev/js/index.js:14825:3)
    at http://localhost:8000/dev/js/index.js:17504:11
    at forEach (http://localhost:8000/dev/js/index.js:13292:20)
    at loadModules (http://localhost:8000/dev/js/index.js:17479:5)
    at http://localhost:8000/dev/js/index.js:17496:40
    at forEach (http://localhost:8000/dev/js/index.js:13292:20)
    at loadModules (http://localhost:8000/dev/js/index.js:17479:5)
    at createInjector (http://localhost:8000/dev/js/index.js:17401:19)
http://errors.angularjs.org/1.5.2/$injector/modulerr?p0=%7B%22_invokeQueue%22%3A%5B%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22sfPath%22%2C%221%22%3A%5Bnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22sfBuilder%22%2C%221%22%3A%5B%22sfPathProvider%22%2Cnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22schemaFormDecorators%22%2C%221%22%3A%5B%22%24compileProvider%22%2C%22sfPathProvider%22%2Cnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22sfErrorMessage%22%7D%5D%2C%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22schemaForm%22%2C%221%22%3A%5B%22sfPathProvider%22%2Cnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22factory%22%2C%7B%220%22%3A%22sfSelect%22%2C%221%22%3A%5B%22sfPath%22%2Cnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22factory%22%2C%7B%220%22%3A%22sfValidator%22%2C%221%22%3A%5Bnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfArray%22%2C%221%22%3A%5B%22sfSelect%22%2C%22schemaForm%22%2C%22sfValidator%22%2C%22sfPath%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfChanged%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfField%22%2C%221%22%3A%5B%22%24parse%22%2C%22%24compile%22%2C%22%24http%22%2C%22%24templateCache%22%2C%22%24interpolate%22%2C%22%24q%22%2C%22sfErrorMessage%22%2C%22sfPath%22%2C%22sfSelect%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfMessage%22%2C%221%22%3A%5B%22%24injector%22%2C%22sfErrorMessage%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfNewArray%22%2C%221%22%3A%5B%22sfSelect%22%2C%22sfPath%22%2C%22schemaForm%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfSchema%22%2C%221%22%3A%5B%22%24compile%22%2C%22%24http%22%2C%22%24templateCache%22%2C%22%24q%22%2C%22schemaForm%22%2C%22schemaFormDecorators%22%2C%22sfSelect%22%2C%22sfPath%22%2C%22sfBuilder%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22schemaValidate%22%2C%221%22%3A%5B%22sfValidator%22%2C%22%24parse%22%2C%22sfSelect%22%2Cnull%5D%7D%5D%5D%2C%22_configBlocks%22%3A%5B%5D%2C%22_runBlocks%22%3A%5B%5D%2C%22requires%22%3A%5B%5D%2C%22name%22%3A%22schemaForm%22%7D&p1=Error%3A%20%5Bng%3Aareq%5D%20Argument%20'module'%20is%20not%20a%20function%2C%20got%20Object%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.2%2Fng%2Fareq%3Fp0%3Dmodule%26p1%3Dnot%2520a%2520function%252C%2520got%2520Object%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A13039%3A12%0A%20%20%20%20at%20assertArg%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A14815%3A11)%0A%20%20%20%20at%20assertArgFn%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A14825%3A3)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17504%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A13292%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17479%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17496%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A13292%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17479%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17401%3A19)
    at http://localhost:8000/dev/js/index.js:13039:12
    at http://localhost:8000/dev/js/index.js:17518:15
    at forEach (http://localhost:8000/dev/js/index.js:13292:20)
    at loadModules (http://localhost:8000/dev/js/index.js:17479:5)
    at http://localhost:8000/dev/js/index.js:17496:40
    at forEach (http://localhost:8000/dev/js/index.js:13292:20)
    at loadModules (http://localhost:8000/dev/js/index.js:17479:5)
    at createInjector (http://localhost:8000/dev/js/index.js:17401:19)
    at doBootstrap (http://localhost:8000/dev/js/index.js:14681:20)
    at Object.bootstrap (http://localhost:8000/dev/js/index.js:14702:12)
http://errors.angularjs.org/1.5.2/$injector/modulerr?p0=myApp.main&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20%7B%22_invokeQueue%22%3A%5B%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22sfPath%22%2C%221%22%3A%5Bnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22sfBuilder%22%2C%221%22%3A%5B%22sfPathProvider%22%2Cnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22schemaFormDecorators%22%2C%221%22%3A%5B%22%24compileProvider%22%2C%22sfPathProvider%22%2Cnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22sfErrorMessage%22%7D%5D%2C%5B%22%24provide%22%2C%22provider%22%2C%7B%220%22%3A%22schemaForm%22%2C%221%22%3A%5B%22sfPathProvider%22%2Cnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22factory%22%2C%7B%220%22%3A%22sfSelect%22%2C%221%22%3A%5B%22sfPath%22%2Cnull%5D%7D%5D%2C%5B%22%24provide%22%2C%22factory%22%2C%7B%220%22%3A%22sfValidator%22%2C%221%22%3A%5Bnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfArray%22%2C%221%22%3A%5B%22sfSelect%22%2C%22schemaForm%22%2C%22sfValidator%22%2C%22sfPath%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfChanged%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfField%22%2C%221%22%3A%5B%22%24parse%22%2C%22%24compile%22%2C%22%24http%22%2C%22%24templateCache%22%2C%22%24interpolate%22%2C%22%24q%22%2C%22sfErrorMessage%22%2C%22sfPath%22%2C%22sfSelect%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfMessage%22%2C%221%22%3A%5B%22%24injector%22%2C%22sfErrorMessage%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfNewArray%22%2C%221%22%3A%5B%22sfSelect%22%2C%22sfPath%22%2C%22schemaForm%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sfSchema%22%2C%221%22%3A%5B%22%24compile%22%2C%22%24http%22%2C%22%24templateCache%22%2C%22%24q%22%2C%22schemaForm%22%2C%22schemaFormDecorators%22%2C%22sfSelect%22%2C%22sfPath%22%2C%22sfBuilder%22%2Cnull%5D%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22schemaValidate%22%2C%221%22%3A%5B%22sfValidator%22%2C%22%24parse%22%2C%22sfSelect%22%2Cnull%5D%7D%5D%5D%2C%22_configBlocks%22%3A%5B%5D%2C%22_runBlocks%22%3A%5B%5D%2C%22requires%22%3A%5B%5D%2C%22name%22%3A%22schemaForm%22%7D%20due%20to%3A%0AError%3A%20%5Bng%3Aareq%5D%20Argument%20'module'%20is%20not%20a%20function%2C%20got%20Object%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.2%2Fng%2Fareq%3Fp0%3Dmodule%26p1%3Dnot%2520a%2520function%252C%2520got%2520Object%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A13039%3A12%0A%20%20%20%20at%20assertArg%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A14815%3A11)%0A%20%20%20%20at%20assertArgFn%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A14825%3A3)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17504%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A13292%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17479%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17496%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A13292%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17479%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17401%3A19)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.2%2F%24injector%2Fmodulerr%3Fp0%3D%257B%2522_invokeQueue%2522%253A%255B%255B%2522%2524provide%2522%252C%2522provider%2522%252C%257B%25220%2522%253A%2522sfPath%2522%252C%25221%2522%253A%255Bnull%255D%257D%255D%252C%255B%2522%2524provide%2522%252C%2522provider%2522%252C%257B%25220%2522%253A%2522sfBuilder%2522%252C%25221%2522%253A%255B%2522sfPathProvider%2522%252Cnull%255D%257D%255D%252C%255B%2522%2524provide%2522%252C%2522provider%2522%252C%257B%25220%2522%253A%2522schemaFormDecorators%2522%252C%25221%2522%253A%255B%2522%2524compileProvider%2522%252C%2522sfPathProvider%2522%252Cnull%255D%257D%255D%252C%255B%2522%2524provide%2522%252C%2522provider%2522%252C%257B%25220%2522%253A%2522sfErrorMessage%2522%257D%255D%252C%255B%2522%2524provide%2522%252C%2522provider%2522%252C%257B%25220%2522%253A%2522schemaForm%2522%252C%25221%2522%253A%255B%2522sfPathProvider%2522%252Cnull%255D%257D%255D%252C%255B%2522%2524provide%2522%252C%2522factory%2522%252C%257B%25220%2522%253A%2522sfSelect%2522%252C%25221%2522%253A%255B%2522sfPath%2522%252Cnull%255D%257D%255D%252C%255B%2522%2524provide%2522%252C%2522factory%2522%252C%257B%25220%2522%253A%2522sfValidator%2522%252C%25221%2522%253A%255Bnull%255D%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522sfArray%2522%252C%25221%2522%253A%255B%2522sfSelect%2522%252C%2522schemaForm%2522%252C%2522sfValidator%2522%252C%2522sfPath%2522%252Cnull%255D%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522sfChanged%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522sfField%2522%252C%25221%2522%253A%255B%2522%2524parse%2522%252C%2522%2524compile%2522%252C%2522%2524http%2522%252C%2522%2524templateCache%2522%252C%2522%2524interpolate%2522%252C%2522%2524q%2522%252C%2522sfErrorMessage%2522%252C%2522sfPath%2522%252C%2522sfSelect%2522%252Cnull%255D%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522sfMessage%2522%252C%25221%2522%253A%255B%2522%2524injector%2522%252C%2522sfErrorMessage%2522%252Cnull%255D%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522sfNewArray%2522%252C%25221%2522%253A%255B%2522sfSelect%2522%252C%2522sfPath%2522%252C%2522schemaForm%2522%252Cnull%255D%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522sfSchema%2522%252C%25221%2522%253A%255B%2522%2524compile%2522%252C%2522%2524http%2522%252C%2522%2524templateCache%2522%252C%2522%2524q%2522%252C%2522schemaForm%2522%252C%2522schemaFormDecorators%2522%252C%2522sfSelect%2522%252C%2522sfPath%2522%252C%2522sfBuilder%2522%252Cnull%255D%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522schemaValidate%2522%252C%25221%2522%253A%255B%2522sfValidator%2522%252C%2522%2524parse%2522%252C%2522sfSelect%2522%252Cnull%255D%257D%255D%255D%252C%2522_configBlocks%2522%253A%255B%255D%252C%2522_runBlocks%2522%253A%255B%255D%252C%2522requires%2522%253A%255B%255D%252C%2522name%2522%253A%2522schemaForm%2522%257D%26p1%3DError%253A%2520%255Bng%253Aareq%255D%2520Argument%2520'module'%2520is%2520not%2520a%2520function%252C%2520got%2520Object%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.2%252Fng%252Fareq%253Fp0%253Dmodule%2526p1%253Dnot%252520a%252520function%25252C%252520got%252520Object%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A13039%253A12%250A%2520%2520%2520%2520at%2520assertArg%2520(http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A14815%253A11)%250A%2520%2520%2520%2520at%2520assertArgFn%2520(http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A14825%253A3)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A17504%253A11%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A13292%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A17479%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A17496%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A13292%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A17479%253A5)%250A%2520%2520%2520%2520at%2520createInjector%2520(http%253A%252F%252Flocalhost%253A8000%252Fdev%252Fjs%252Findex.js%253A17401%253A19)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A13039%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17518%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A13292%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17479%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17496%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A13292%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17479%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A17401%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A14681%3A20)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2Flocalhost%3A8000%2Fdev%2Fjs%2Findex.js%3A14702%3A12)(anonymous function) @ angular.js:68(anonymous function) @ angular.js:4547forEach @ angular.js:321loadModules @ angular.js:4508createInjector @ angular.js:4430doBootstrap @ angular.js:1710bootstrap @ angular.js:1731226.../gen/config @ index.js:68s @ _prelude.js:1e @ _prelude.js:1(anonymous function) @ _prelude.js:1
```

**Comment by Anthropic** [comment]
You will need to replicate this in plunker or gist for someone to provide the support you are after. Otherwise I would assume, as it claims module is not a function, that you haven't loaded the files in the right order.

**Comment by Anthropic** [comment]
I don't use browserify myself, which is why I need a demo to provide better support. :)

**Comment by Alain1405** [comment]
Thanks @Anthropic but I just solved. I'm also not an expert with Browserify, I just inherited a project which uses it.
In the end I didn't need to include the returning value of `require`, but just the module name (not even that for the decorators):
```
require('angular-schema-form');
require('angular-schema-form-bootstrap');
...
module.exports = angular.module('myApp.resources', ['schemaForm', angularResource])
...
```

**Comment by Anthropic** [comment]
Thanks @Alain1405, we appreciate follow up and your time for closing the issue :)
