### ISSUE TITLE
getting updateOn undefined error when using restangular in my config file

### ISSUE THREAD

**Issue by guptasuraj** [json-schema-form/angular-schema-form#819]
TypeError: Cannot read property 'updateOn' of undefined
    at new controller (http://localhost:8099/static/vendor/angular/angular.js:28239:34)
    at Object.invoke (http://localhost:8099/static/vendor/angular/angular.js:4718:19)
    at $controllerInit (http://localhost:8099/static/vendor/angular/angular.js:10354:34)
    at nodeLinkFn (http://localhost:8099/static/vendor/angular/angular.js:9263:34)
    at compositeLinkFn (http://localhost:8099/static/vendor/angular/angular.js:8620:13)
    at publicLinkFn (http://localhost:8099/static/vendor/angular/angular.js:8500:30)
    at lazyCompilation (http://localhost:8099/static/vendor/angular/angular.js:8844:25)
    at boundTranscludeFn (http://localhost:8099/static/vendor/angular/angular.js:8637:16)
    at controllersBoundTransclude (http://localhost:8099/static/vendor/angular/angular.js:9385:20)
    at Object.ngTranscludePostLink (http://localhost:8099/static/vendor/angular/angular.js:30686:9) <div class="search-filter__input" ng-transclude="">

**Comment by Anthropic** [comment]
@guptasuraj which version? Can you provide an example/demo?

**Comment by guptasuraj** [comment]
i am using angular v1.3.15 and restangular v1.5.2

**Comment by Anthropic** [comment]
@guptasuraj which version of Angular Schema Form? Can you make a plunker or demo with the files you are using?

**Comment by Anthropic** [comment]
Please re-open if you have more info, I'm spring cleaning quiet issues.
