### ISSUE TITLE
Unable to load schemaForm (angular/webpack)

### ISSUE THREAD

**Issue by AChakraborty1982** [json-schema-form/angular-schema-form#883]
angular.js:2101Uncaught Error: [$injector:nomod] http://errors.angularjs.org/1.5.6/$injector/nomod?p0=schemaForm(…)
angular.js:13642TypeError: Cannot read property 'text' of undefined
    at http://localhost:8123/node_modules/angular-schema-form/dist/schema-form.min.js:1:4011
    at Array.reduce (native)
    at l (http://localhost:8123/node_modules/angular-schema-form/dist/schema-form.min.js:1:3961)
    at Object.build (http://localhost:8123/node_modules/angular-schema-form/dist/schema-form.min.js:1:4692)
    at g (http://localhost:8123/node_modules/angular-schema-form/dist/schema-form.min.js:1:28129)
    at y (http://localhost:8123/node_modules/angular-schema-form/dist/schema-form.min.js:1:27710)
    at http://localhost:8123/node_modules/angular-schema-form/dist/schema-form.min.js:1:28592
    at m.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:142:305)
    at m.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:145:401)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:21:117

i have attached the project 

[ngschemaforms.zip](https://github.com/json-schema-form/angular-schema-form/files/1007670/ngschemaforms.zip)

**Comment by Anthropic** [comment]
@AChakraborty1982 I don't accept zip files, if you make a plunk I can take a look, but the error indicates the file isn't included and if it is then in the wrong order. If you need help with webpack you may have better luck there as they have more resources than I do to help you.

Please feel free to re-open with a plunk reference.
