### ISSUE TITLE
npm test  failed

### ISSUE THREAD

**Issue by vsymguysung** [json-schema-form/angular-schema-form#938]
This is error  message

```
/Users/.../angular-schema-form/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/.../angular-schema-form/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/.../angular-schema-form/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:624:30)

```
Any idea?
Thank you!
@json-schema-form/angular-schema-form-lead

**Comment by vsymguysung** [comment]
Never mind. It works on the dev branch though and the error above is only for the master branch.

**Comment by Anthropic** [comment]
Thanks for the follow up @vsymguysung
